### ISSUE TITLE
Support for 2.4 ?

### ISSUE THREAD

**Issue by pawmart** [basecom/CronjobBundle#2]
Is there any reason why we limit this to SF 2.3?

**Comment by sweikenb** [comment]
Hey, no there are no special reasons for that, except that the bundle wasn't tested for that version. I will do this today and create an update for that :)

**Comment by sweikenb** [comment]
Update done, there you go: https://github.com/basecom/CronjobBundle/blob/2.4.0/composer.json and thanks for the hint!
